### ISSUE TITLE
Can't access admin

### ISSUE THREAD

**Issue by seb-b** [coderedcorp/wagtail-cache#11]
The html files are missing from the MANIFEST.in so they aren't included in the package from pypi, resulting in a missing template error.

```Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
                  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
          response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
              return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
              return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wagtailcache/views.py", line 16, in index
      return render(request, 'wagtailcache/index.html', {'cache_icon': CACHE_ICON})
  File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
      content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
          template = get_template(template_name, using=using)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
      raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: wagtailcache/index.html```

**Comment by seb-b** [comment]
Yep my bad! Time to update my deps
